#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
输入输出工具模块
提供文件读写、数据保存等功能
"""

import os
import numpy as np
import cv2
import json
from datetime import datetime


def save_results(structure, colors, output_path):
    """
    保存重建结果

    Args:
        structure: 3D点云 (N x 3)
        colors: 点云颜色 (N x 3)
        output_path: 输出目录路径
    """
    # 创建输出目录
    os.makedirs(output_path, exist_ok=True)

    # 保存numpy格式（方便后续读取）
    np.save(os.path.join(output_path, 'structure.npy'), structure)
    np.save(os.path.join(output_path, 'colors.npy'), colors)

    # 保存PLY格式（可用MeshLab、CloudCompare等软件打开）
    save_ply(os.path.join(output_path, 'point_cloud.ply'), structure, colors)

    # 保存OBJ格式（可用于Blender、Maya等）
    save_obj(os.path.join(output_path, 'point_cloud.obj'), structure, colors)

    # 保存文本格式（便于查看）
    save_txt(os.path.join(output_path, 'point_cloud.txt'), structure, colors)

    # 保存统计信息
    save_statistics(os.path.join(output_path, 'statistics.json'),
                    structure, colors)

    print(f"Results saved to: {output_path}")


def save_ply(filepath, points, colors=None):
    """
    保存为PLY格式（最常用的点云格式）

    Args:
        filepath: 保存路径
        points: Nx3的点云坐标
        colors: Nx3的颜色值（RGB，0-255）
    """
    with open(filepath, 'w') as f:
        # 写入头部
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write(f"element vertex {len(points)}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")

        if colors is not None:
            f.write("property uchar red\n")
            f.write("property uchar green\n")
            f.write("property uchar blue\n")

        f.write("end_header\n")

        # 写入数据
        for i in range(len(points)):
            x, y, z = points[i]
            f.write(f"{x} {y} {z}")

            if colors is not None:
                # 确保颜色值在0-255范围内
                if len(colors.shape) == 1:
                    r = g = b = int(colors[i])
                else:
                    r, g, b = colors[i].astype(np.uint8)
                f.write(f" {r} {g} {b}")

            f.write("\n")

    print(f"Saved PLY file: {filepath}")


def save_obj(filepath, points, colors=None):
    """
    保存为OBJ格式（常用于三维模型）

    Args:
        filepath: 保存路径
        points: Nx3的点云坐标
        colors: Nx3的颜色值（可选）
    """
    with open(filepath, 'w') as f:
        # 写入注释
        f.write("# 3D Reconstruction Point Cloud\n")
        f.write(f"# Generated by SFM Pipeline\n")
        f.write(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"# Number of points: {len(points)}\n\n")

        # 写入顶点
        for i, point in enumerate(points):
            x, y, z = point
            f.write(f"v {x} {y} {z}")

            # 如果有颜色，写入颜色信息
            if colors is not None:
                if len(colors.shape) == 1:
                    r = g = b = colors[i]
                else:
                    r, g, b = colors[i]
                f.write(f" {r / 255.0} {g / 255.0} {b / 255.0}")

            f.write("\n")

    print(f"Saved OBJ file: {filepath}")


def save_txt(filepath, points, colors=None):
    """
    保存为TXT格式（便于查看）

    Args:
        filepath: 保存路径
        points: Nx3的点云坐标
        colors: Nx3的颜色值（可选）
    """
    with open(filepath, 'w') as f:
        f.write("# X\tY\tZ")
        if colors is not None:
            f.write("\tR\tG\tB")
        f.write("\n")

        for i in range(len(points)):
            x, y, z = points[i]
            f.write(f"{x:.6f}\t{y:.6f}\t{z:.6f}")

            if colors is not None:
                if len(colors.shape) == 1:
                    r = g = b = colors[i]
                else:
                    r, g, b = colors[i]
                f.write(f"\t{r:.0f}\t{g:.0f}\t{b:.0f}")

            f.write("\n")

    print(f"Saved TXT file: {filepath}")


def save_statistics(filepath, structure, colors):
    """
    保存统计信息为JSON格式

    Args:
        filepath: 保存路径
        structure: 3D点云
        colors: 点云颜色
    """
    stats = {
        'total_points': len(structure),
        'points_with_color': len(colors) if colors is not None else 0,
        'bbox': {
            'x_min': float(np.min(structure[:, 0])),
            'x_max': float(np.max(structure[:, 0])),
            'y_min': float(np.min(structure[:, 1])),
            'y_max': float(np.max(structure[:, 1])),
            'z_min': float(np.min(structure[:, 2])),
            'z_max': float(np.max(structure[:, 2]))
        },
        'center': {
            'x': float(np.mean(structure[:, 0])),
            'y': float(np.mean(structure[:, 1])),
            'z': float(np.mean(structure[:, 2]))
        },
        'generated_time': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }

    with open(filepath, 'w') as f:
        json.dump(stats, f, indent=4)

    print(f"Saved statistics: {filepath}")


def load_results(output_path):
    """
    加载保存的重建结果

    Args:
        output_path: 输出目录路径

    Returns:
        structure: 3D点云
        colors: 点云颜色
    """
    structure_path = os.path.join(output_path, 'structure.npy')
    colors_path = os.path.join(output_path, 'colors.npy')

    if not os.path.exists(structure_path):
        raise FileNotFoundError(f"Structure file not found: {structure_path}")

    structure = np.load(structure_path)
    colors = np.load(colors_path) if os.path.exists(colors_path) else None

    print(f"Loaded {len(structure)} points from {output_path}")
    return structure, colors


def save_camera_parameters(filepath, rotations, motions, K):
    """
    保存相机参数

    Args:
        filepath: 保存路径
        rotations: 旋转矩阵列表
        motions: 平移向量列表
        K: 相机内参矩阵
    """
    camera_data = {
        'intrinsic_matrix': K.tolist(),
        'num_cameras': len(rotations),
        'cameras': []
    }

    for i in range(len(rotations)):
        camera_data['cameras'].append({
            'index': i,
            'rotation': rotations[i].tolist(),
            'translation': motions[i].flatten().tolist()
        })

    with open(filepath, 'w') as f:
        json.dump(camera_data, f, indent=4)

    print(f"Saved camera parameters: {filepath}")


def load_camera_parameters(filepath):
    """
    加载相机参数

    Args:
        filepath: 保存路径

    Returns:
        rotations: 旋转矩阵列表
        motions: 平移向量列表
        K: 相机内参矩阵
    """
    with open(filepath, 'r') as f:
        camera_data = json.load(f)

    K = np.array(camera_data['intrinsic_matrix'])
    rotations = []
    motions = []

    for cam in camera_data['cameras']:
        rotations.append(np.array(cam['rotation']))
        motions.append(np.array(cam['translation']).reshape(-1, 1))

    return rotations, motions, K


def save_performance_report(filepath, timings, reproj_error,
                            points_before, points_after):
    """
    保存性能报告

    Args:
        filepath: 保存路径
        timings: 各阶段耗时字典
        reproj_error: 重投影误差
        points_before: BA前点数
        points_after: BA后点数
    """
    report = {
        'timing': timings,
        'total_time': sum(timings.values()),
        'reprojection_error': reproj_error,
        'points_before_ba': points_before,
        'points_after_ba': points_after,
        'points_removed': points_before - points_after,
        'generated_time': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }

    with open(filepath, 'w') as f:
        json.dump(report, f, indent=4)

    print(f"Saved performance report: {filepath}")